#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# setup-vcpkg.sh — Cross-compile libosmscout dependencies for Android
#
# Installs vcpkg and builds all native dependencies needed by
# libosmscout for Android target ABIs.
#
# Usage:  ./setup-vcpkg.sh [--triplet arm64-android]
#
# Default triplet: arm64-android (add more: arm-neon-android x64-android)
# ──────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vcpkg location: VCPKG_ROOT env var wins, otherwise project-local
VCPKG_DIR="${VCPKG_ROOT:-$SCRIPT_DIR/vcpkg}"

if [ $# -eq 0 ]; then
    TRIPLETS=(arm64-android arm-neon-android x64-android)
else
    TRIPLETS=("$@")
fi

# ── Parse local.properties ────────────────────────────────────
LOCAL_PROP="$SCRIPT_DIR/local.properties"
if [ -f "$LOCAL_PROP" ]; then
    SDK_DIR=$(grep "^sdk\.dir=" "$LOCAL_PROP" | cut -d= -f2- | xargs)
    JAVA_HOME=$(grep "^org\.gradle\.java\.home=" "$LOCAL_PROP" | cut -d= -f2- | xargs)

    if [ -n "$SDK_DIR" ]; then
        export ANDROID_SDK_ROOT="$SDK_DIR"
        echo "  ANDROID_SDK_ROOT ← $SDK_DIR (from local.properties)"
    fi
    if [ -n "$JAVA_HOME" ]; then
        export JAVA_HOME="$JAVA_HOME"
        echo "  JAVA_HOME         ← $JAVA_HOME (from local.properties)"
    fi
fi

# Derive NDK_HOME from SDK if not already set
if [ -z "${ANDROID_NDK_HOME:-}" ] && [ -n "${ANDROID_SDK_ROOT:-}" ]; then
    NDK_VERSION=$(ls "$ANDROID_SDK_ROOT/ndk/" 2>/dev/null | sort -V | tail -1)
    if [ -n "$NDK_VERSION" ]; then
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/$NDK_VERSION"
        echo "  ANDROID_NDK_HOME  ← $ANDROID_NDK_HOME (derived)"
    fi
fi
echo ""

echo "=== NaviVeylin: vcpkg Native Dependencies ==="
echo ""

# ── 1. Clone vcpkg ───────────────────────────────────────────
if [ -d "$VCPKG_DIR" ] && [ -f "$VCPKG_DIR/vcpkg" ]; then
    echo "[1/4] vcpkg already present at $VCPKG_DIR"
else
    echo "[1/4] Cloning vcpkg..."
    git clone https://github.com/microsoft/vcpkg.git "$VCPKG_DIR"
fi

# ── 2. Bootstrap vcpkg ───────────────────────────────────────
echo "[2/4] Bootstrapping vcpkg..."
cd "$VCPKG_DIR"
./bootstrap-vcpkg.sh -disableMetrics

# ── 3. Install dependencies per triplet ──────────────────────
echo "[3/4] Installing dependencies for Android..."
echo "      Triplets: ${TRIPLETS[*]}"
echo ""

DEPS=(
    # NOTE: libosmscout itself is intentionally NOT installed via vcpkg —
    # it is built from the source submodule. The vcpkg libosmscout package
    # used to shadow the submodule headers during the NDK build (stale
    # osmscout/*.h under installed/<triplet>/include won over the submodule
    # headers) and crashed vcpkg mid-install, corrupting installed state.
    marisa-trie
    cairo
    pango
    harfbuzz
    fribidi
    libpng
    freetype
    fontconfig
    protobuf
    libxml2
    zlib
)

for triplet in "${TRIPLETS[@]}"; do
    echo "  ── $triplet ──"
    for dep in "${DEPS[@]}"; do
        echo "    Installing $dep:$triplet ..."
        ./vcpkg install "$dep:$triplet" --recurse --overlay-ports="$SCRIPT_DIR/vcpkg-overlays" --overlay-triplets="$SCRIPT_DIR/vcpkg-overlays/triplets" || echo "    ⚠  $dep:$triplet failed (may not be in registry)"
    done
    echo ""
done

# ── 4. Generate CMake toolchain file ──────────────────────────
echo "[4/4] Writing CMake toolchain wrapper..."
TOOLCHAIN_FILE="$SCRIPT_DIR/app/src/main/cpp/android-toolchain.cmake"

cat > "$TOOLCHAIN_FILE" << TOOLCHAIN_EOF
# Android NDK toolchain wrapper for vcpkg
# Generated by setup-vcpkg.sh — do not edit manually

set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 26)
set(CMAKE_ANDROID_NDK \$ENV{ANDROID_NDK_HOME}
    CACHE PATH "Android NDK path")

# Point CMake to vcpkg's toolchain
set(VCPKG_TARGET_TRIPLET arm64-android
    CACHE STRING "vcpkg triplet for Android")

if(DEFINED ENV{VCPKG_ROOT})
    set(CMAKE_TOOLCHAIN_FILE "\$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
        CACHE FILEPATH "vcpkg CMake toolchain")
else()
    message(FATAL_ERROR "Set VCPKG_ROOT to the vcpkg directory before building")
endif()
TOOLCHAIN_EOF

echo "      ✓ $TOOLCHAIN_FILE"
echo ""
echo "=== Done ==="
echo ""
echo "Installed packages per triplet:"
for triplet in "${TRIPLETS[@]}"; do
    INSTALLED_DIR="$VCPKG_DIR/installed/$triplet"
    if [ -d "$INSTALLED_DIR" ]; then
        COUNT=$(find "$INSTALLED_DIR/lib/pkgconfig" -name "*.pc" 2>/dev/null | wc -l)
        echo "  $triplet: $COUNT packages"
        echo "    $(ls "$INSTALLED_DIR/lib/pkgconfig/" 2>/dev/null | sed 's/\.pc$//' | tr '\n' ' ')"
        echo ""
    else
        echo "  $triplet: (not installed)"
    fi
done

# Check required packages (note: .pc file names differ from package names)
declare -A PKG_MAP=(
    [cairo]=cairo
    [marisa-trie]=marisa
    [pango]=pango
    [harfbuzz]=harfbuzz
    [fribidi]=fribidi
    [libpng]=libpng
    [freetype]=freetype2
    [fontconfig]=fontconfig
    [protobuf]=protobuf
    [libxml2]=libxml-2.0
    [zlib]=zlib
)
MISSING=()
for pkg in "${!PKG_MAP[@]}"; do
    pc="${PKG_MAP[$pkg]}.pc"
    FOUND=false
    for triplet in "${TRIPLETS[@]}"; do
        if [ -f "$VCPKG_DIR/installed/$triplet/lib/pkgconfig/$pc" ]; then
            FOUND=true
            break
        fi
    done
    if [ "$FOUND" = false ]; then
        MISSING+=("$pkg")
    fi
done

if [ ${#MISSING[@]} -eq 0 ]; then
    echo "All required packages installed. ✓"
else
    echo "Missing packages: ${MISSING[*]}"
    echo "Re-run: ./vcpkg install ${MISSING[*]/%/:arm64-android}"
fi
echo ""
echo "To build with vcpkg dependencies:"
echo ""
echo "  cd $SCRIPT_DIR && ./gradlew :app:assembleDebug"
echo ""
echo "Environment is already set from local.properties."
echo ""
echo "vcpkg location: $VCPKG_DIR"
echo "  Override with: export VCPKG_ROOT=/path/to/vcpkg"
echo "If install fails, add an overlay port or use a custom registry."
echo "See: https://github.com/Framstag/libosmscout for build instructions."
echo ""
echo "Cairo + Pango + freetype + fontconfig are required for the Cairo rendering backend."
echo "Pango provides text layout for map labels (street names, POIs)."
echo "All are well-supported in vcpkg for Android."
