# Android NDK toolchain wrapper for vcpkg
# Generated by setup-vcpkg.sh — do not edit manually

set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 26)
set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_HOME}
    CACHE PATH "Android NDK path")

# Point CMake to vcpkg's toolchain
set(VCPKG_TARGET_TRIPLET arm64-android
    CACHE STRING "vcpkg triplet for Android")

if(DEFINED ENV{VCPKG_ROOT})
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
        CACHE FILEPATH "vcpkg CMake toolchain")
else()
    message(FATAL_ERROR "Set VCPKG_ROOT to the vcpkg directory before building")
endif()
